### ISSUE TITLE
Plotting data of ongoing 2D scan

### ISSUE THREAD

**Issue by danielbouman** [Rubenknex/qtplot#14]
When opening an x*y dataset of an ongoing scan, qtplot fails to plot if the datafile is empty, or when the 2nd or 3rd y-data line being taken. When the 1st y-data line is being taken, the data is plotted. When one refreshes however during 2nd or 3rd y-data scan, an error is thrown and the plot window is not updated. After the 3rd y-data line, the plot window can be updated once again. 

Traceback of the error when updating during the 2nd or 3rd y-data line scan:

``` python
Traceback (most recent call last):
  File "c:\anaconda2\lib\site-packages\qtplot\qtplot.py", line 621, in on_data_c
hange
    self.canvas.set_data(self.data)
  File "c:\anaconda2\lib\site-packages\qtplot\canvas.py", line 130, in set_data
    vertices = self.generate_vertices(data)
  File "c:\anaconda2\lib\site-packages\qtplot\canvas.py", line 165, in generate_
vertices
    xq, yq = data.get_quadrilaterals(data.x, data.y)
  File "c:\anaconda2\lib\site-packages\qtplot\data.py", line 303, in get_quadril
aterals
    t0, t1, t2 = yc[0], yc[1], yc[2]
IndexError: index 2 is out of bounds for axis 0 with size 2
```

**Comment by Rubenknex** [comment]
Fixed, from this point on also only the NaN datapoints will not be plotted, instead of also the datapoints directly below/to the side of them.
